### ISSUE TITLE
New Huge Issue

### ISSUE THREAD

**Issue by AndyHudson7** [kylemkramer/socialhub#1]
When I logged in, I realized that I didn't have an account with ahudson@forbin.com. I must have signed up with my personal email. So now I have a new one under ahudson@forbin.com.

Thanks for getting to this pressing issue!!!!!!!!!!!!

**Comment by kylemkramer** [comment]
This issue has been taken care of in the 1.3.7 roll-out. Try opening it again and refreshing it, it should show the new version.
